build:
command: site
commandOrigin: ui
publish: /opt/build/repo
publishOrigin: default
redirects:
- from: /Project
  status: 301
  to: /pages
- from: /*
      status: 200
      to: /index.html
  redirectsOrigin: config