
[[redirects]]
  from = "/Project"
  to = "/pages"
  status = 301  # redirecionamento permanente

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200  # necessário para SPAs (React, Vue, etc.)
